name: restopass
description: RestoPass est une application qui permet aux étudiants d'acheter leur tichets en ligne.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^1.0.7
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
  sleek_circular_slider: ^1.2.0+web
  modal_bottom_sheet: ^1.0.0+1
  rolling_nav_bar: ^0.0.2
  polygon_clipper: ^1.0.2
  url_launcher: ^5.7.10
  flutter_local_notifications: ^3.0.2
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.0
  fluttertoast: ^7.1.6
  material_snackbar: ^1.2.1
  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  pretty_qr_code: ^1.0.1
  flutter_barcode_scanner: ^1.0.2
  flutter_money_formatter: ^0.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf