name: restopass
description: RestoPass est une application qui permet aux étudiants d'acheter leur tichets en ligne.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  iconly: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  phosphor_flutter: ^2.0.0
  get: ^4.6.6
  dio: ^5.3.3
  get_storage: ^2.1.1
  device_info_plus: ^10.1.0
  flutter_svg: ^2.0.8
  shimmer: ^3.0.0
  geolocator: ^10.1.0
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.3
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^2.24.2
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.3.7
  flutter_slidable: ^3.1.0
  firebase_messaging: ^14.7.19
  awesome_notifications: ^0.9.3+1
  timeago: ^3.6.1
  webview_flutter: ^4.8.0
  fluttertoast: ^8.2.6
  sleek_circular_slider: ^2.0.1
  shared_preferences: ^2.2.3
  flutter_webview_plugin: ^0.4.0
  pretty_qr_code: ^3.3.0
  url_launcher: ^6.3.0
  flutter_barcode_scanner: ^2.0.0
  flutter_local_notifications: ^17.2.1
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
